spring:
  application:
    name: backend-assignment

  datasource:
    url: jdbc:mysql://localhost:3306/allra?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:9181}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true # 데이터 초기화 시점 조정 (스키마 생성 후 데이터 삽입)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql: 
    init:
      mode: always # 앱 실행 시 data.sql 항상 실행

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    tags-sorter: none       # 태그 정렬 비활성화 (수동 순서 유지)
    operations-sorter: none # 엔드포인트 정렬 비활성화 (선언 순서 유지)
    disable-swagger-default-url: true  # Swagger 기본 URL 비활성화
  api-docs:
    path: /v3/api-docs       # OpenAPI 문서 기본 경로 (기본값이지만 명시적으로 유지)
logging:
  level:
    org.springframework.web.servlet.resource.ResourceHttpRequestHandler: off

# 외부 API / Mock API 설정
webclient:
  mock-base-url: ${MOCK_BASE_URL:http://localhost:8080}


